# NATS.io is a lightweight and high-performance messaging system that
# provides publish-subscribe and request-reply messaging patterns.
# It is designed for building distributed systems and microservices architectures.
services:
  nats:
    image: nats:alpine
    command: -c /etc/nats/config.conf
    volumes:
      - ./config.conf:/etc/nats/config.conf:ro
      - ./resolver.conf:/etc/nats/resolver.conf:ro
      - ./certs:/etc/nats/certs
      - nats_data:/data
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    ports:
      - "7777:7777"
    command: -varz -connz -routez -subz -prefix=nats -jsz all "http://nats:8222"
    depends_on:
      - nats

volumes:
  nats_data:
