services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    environment:
      - QDB_METRICS_ENABLED=TRUE
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
