changelog:
  categories:
    - title: "🛰️ Overview"
      labels:
        - "-"
    - title: "🚀 Features/Enhancements"
      labels:
        - "feature"
        - "enhancement"
    - title: "⚙️ Refactor"
      labels:
        - "refactor"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bugfix"
        - "bug"
    - title: "🖥️ Ergonomics"
      labels:
        - "ergonomics"
    - title: "🏗️ Breaking Changes"
      labels:
        - "breaking-change"
    - title: "📚 Documentation"
      labels:
        - "documentation"
    - title: "⚡ Performance"
      labels:
        - "performance"
    - title: "🧪 Tests"
      labels:
        - "test"
        - "testing"
    - title: Other Changes
      labels:
        - "*"
