# Swarm File Definition
#  Used to defined a set of swarms to mimic devices
#  Can be used for integration and performance testing or demos
apiVersion: mir/v1alpha
kind: swarm
meta:
  # Name and Namespace are used for schema package name
  name: "local"
  namespace: "swarm"
  labels: {}
  annotations: {}
swarm:
  logLevel: info
  devices:
    - count: 2
      meta:
        name: reco # Used as prefix with __{i} if more then one
        namespace: swarm
        annotations:
          swarm: "true"
      telemetry:
        - name: Environment # Schema message name
          interval: 3s # Send interval
          tags: {} # Becomes schema message tags
          fields: # Refers to Telemetry fields definition
            - temperature
            - humidity
            - pressure
        - name: Power
          interval: 3s
          tags: {}
          fields:
            - ampere
            - voltage
            - power
        - name: Consumption
          interval: 3s
          tags: {}
          fields:
            - consumption
      commands:
        - name: ActivateHVAC
          delay: 2s
          tags: {}
          fields:
            - power
        - name: SetSensorTemp
          delay: 1s
          tags: {}
          fields:
            - temperature
  # Telemetry fields are a message fields of
  # value type with a attached generator function
  # or a message type pointing to other fields for compositions
  fields:
    - name: consumption # Field name
      type: message # [message|int8|int16|int32|int64|float32|float64]
      fields: # If message, point to other fields
        - power
        - gaz
    - name: gaz
      type: float64
      tags: # List of annotations on a field schema
        unit: m3
      generator: # Telemetry generator options
        # Any math expression, t=time.Now and is required.
        # Supported functions or variables:
        #   - sin, cos, tan, abs, sqrt
        #   - pow, exp, log, log10, floor
        #   - ceil, round, min, max
        #   - pi, π, e, rand, t, x
        expr: "10*sin(t)+3"
    - name: power
      type: float64
      tags:
        unit: W
      generator:
        expr: "10*cos(t)+3"
    - name: voltage
      type: float64
      tags:
        unit: V
      generator:
        expr: "tan(t)+3"
    - name: ampere
      type: float64
      tags:
        unit: A
      generator:
        expr: "10*sin(t)+3.0"
    - name: temperature
      type: float64
      tags:
        unit: C
      generator:
        expr: "10*sin(t)+3.0"
    - name: pressure
      type: float64
      tags:
        unit: Pa
      generator:
        expr: "tan(t)+3.0"
    - name: humidity
      type: float64
      tags:
        unit: "%"
      generator:
        expr: "10*cos(t)+3.0"
