services:
  mir:
    image: ghcr.io/maxthom/mir:${MIR_VERSION:-latest}
    ports:
      - "3015:3015"
    volumes:
      - ./local-config.yaml:/home/mir/.config/mir/mir.yaml
      - ./local-contexts.yaml:/home/mir/.config/mir/cli.yaml
    command: serve
    restart: unless-stopped
