mir:
  logLevel: "info"
  http:
    port: 3015
    tlsCert: ""
    tlsKey: ""
  core:
    enabled: true
    deviceOnlineFlush: 7s
    deviceOfflineFlush: 12s
    deviceOfflineAfter: 30s
  prototlm:
    enabled: true
  protocmd:
    enabled: true
  protocfg:
    enabled: true
  event:
    enabled: true
    flushInterval: 5s
  cockpit:
    enabled: true
    allowedOrigins: []
    githubOwner: MaxThom
    githubRepo: mir
nats:
  url: "nats://local_mir_support-nats-1:4222"
  credentials: ""
  rootCA: ""
  tlsCert: ""
  tlsKey: ""
surreal:
  url: "ws://local_mir_support-surrealdb-1:8000/rpc"
  namespace: "global"
  database: "mir"
  user: "root"
  password: "root"
influx:
  url: "http://local_mir_support-influxdb-1:8086/"
  token: "mir-operator-token"
  org: "Mir"
  bucket: "mir"
  batchSize: 1000
  flushInterval: 1000
  retryBufferLimit: 1073741824
  gzip: false
