mir:
  url: "nats://local_mir_support-nats-1:4222"
  logLevel: "info"
  httpPort: 3015
  credentials: ""
surreal:
  url: "ws://local_mir_support-surrealdb-1:8000/rpc"
  namespace: "global"
  database: "mir"
  user: "root"
  password: "root"
influx:
  url: "http://local_mir_support-influxdb-1:8086/"
  token: "mir-operator-token"
  org: "Mir"
  bucket: "mir"
