default:
    just -l --unsorted

proto:
	mkdir -p proto/gen
	protoc \
	--proto_path=proto/ \
	--go_out=proto/gen \
	--go_opt=paths=source_relative \
	proto/schema/v1/schema.proto

build:
	go build -o bin/device cmd/main.go

run:
	go run cmd/main.go
