{
 "title": "Core",
 "tags": [
  "mir",
  "mir-core",
  "mir-module"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mir_app_info{name=~\"core|mir\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mir_app_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mir_health_alive{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Live Objects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"$instance\"} - go_memstats_frees_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mir_health_ready{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Device Online",
   "type": "timeseries",
   "description": "Number of online devices",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mir_core_device_status_count{instance=\"$instance\", status=\"online\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Device Offline",
   "type": "timeseries",
   "description": "Number of offline devices",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mir_core_device_status_count{instance=\"$instance\", status=\"offline\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of Device Request",
   "type": "timeseries",
   "description": "Number of API device request per route",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_core_request_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Number of Device Request Errors",
   "type": "timeseries",
   "description": "Number of API device request in errors per route",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_core_request_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{system=\"mir\", compose_service=\"mir\"} | cmd = `core` or srv = `core_server`"
    }
   ]
  }
 ]
}