{
 "title": "Mir",
 "tags": [
  "mir",
  "mir-module",
  "mir-overall"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs", "query": "loki" },
   { "name": "job", "label": "Mir", "query": { "query": "label_values(mir_app_info,job)" } },
   {
    "name": "nats",
    "label": "Nats",
    "query": {
     "query": "label_values(nats_varz_version,job)"
    }
   },
   {
    "name": "influx",
    "label": "Influx",
    "query": {
     "query": "label_values(influxdb_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mir_app_info{job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mir_health_alive{job=\"${job}\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Device Status",
   "type": "stat",
   "description": "Number of online and offline devices",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mir_core_device_status_count{job=\"${job}\", status=\"online\"})",
     "legendFormat": "online"
    },
    {
     "expr": "sum(mir_core_device_status_count{job=\"${job}\", status=\"offline\"})",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "max(alertmanager_silences{state=\"active\"})",
     "legendFormat": "Silenced"
    }
   ]
  },
  {
   "title": "Nats Connections",
   "type": "stat",
   "description": "Number of activate connections to Nats Server",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{job=\"${nats}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "gauge",
   "description": "CPU, RAM and Disk space",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"node\"} / node_memory_MemTotal_bytes{job=\"node\"})) * 100",
     "legendFormat": "Ram"
    },
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{job=\"node\",device!~'rootfs'}) * 100) / sum(node_filesystem_size_bytes{job=\"node\",device!~'rootfs'}))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mir_health_ready{job=\"${job}\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Caches",
   "type": "stat",
   "description": "Number of telemetry ingesters in cache",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mir_tlm_timeseries_ingesters_count{job=\"${job}\"})",
     "legendFormat": "Schemas"
    },
    {
     "expr": "sum(mir_schemastore_schema_cache_count{job=\"${job}\"})",
     "legendFormat": "Ingesters"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Live Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mallocs_total{job=\"${job}\"}-go_memstats_frees_total{job=\"${job}\"})"
    }
   ]
  },
  { "title": "Data & Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Data Rate",
   "type": "stat",
   "description": "Telemetry, commands and configuration msg rates",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mir_tlm_datapoint_count{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "Telemetry"
    },
    {
     "expr": "sum(rate(mir_cmd_device_cmd_sent_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "Commands"
    },
    {
     "expr": "sum(rate(mir_cfg_device_desired_props_request_total{job=\"${job}\"}[$__rate_interval])+rate(mir_cfg_device_cfg_sent_total{job=\"${job}\"}[$__rate_interval])+rate(mir_cfg_device_reported_props_request_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "Configuration"
    }
   ]
  },
  {
   "title": "NATS Msgs",
   "type": "stat",
   "description": "Message rates per second in and out of Nats",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_msgs{job=\"${nats}\"}[$__rate_interval])+rate(nats_varz_out_msgs{job=\"${nats}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NATS Data",
   "type": "stat",
   "description": "Message rates per second in and out of Nats",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_bytes{job=\"${nats}\"}[$__rate_interval])+rate(nats_varz_out_bytes{job=\"${nats}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TimeseriesDB Ops",
   "type": "stat",
   "description": "Read and write ops in TimeseriesDB",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(boltdb_writes_total{job=\"${influx}\"}[$__rate_interval]))+sum(rate(boltdb_reads_total{job=\"${influx}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "**Mir System**\n\n*Somewhere, something incredible is waiting to be known - Carl Sagan*\n"
   }
  },
  {
   "title": "Properties Sent to/from Devices",
   "type": "timeseries",
   "description": "Number of desired and reported properties sent to/from devices",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_cfg_sent_total{job=\"${job}\"}[$__rate_interval])+rate(mir_cfg_device_desired_props_request_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "desired properties"
    },
    {
     "expr": "rate(mir_cfg_device_reported_props_request_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "reported properties"
    }
   ]
  },
  {
   "title": "Telemetry Points from Devices",
   "type": "timeseries",
   "description": "Number of telemetry points sent from devices",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "p/sec" } },
   "targets": [
    {
     "expr": "rate(mir_tlm_datapoint_count{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "points"
    },
    {
     "expr": "rate(mir_tlm_datapoint_error_count{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "points error"
    }
   ]
  },
  {
   "title": "Commands Sent to Devices",
   "type": "timeseries",
   "description": "Number of commands sent to devices",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cmd_device_cmd_sent_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "commands"
    },
    {
     "expr": "rate(mir_cmd_device_cmd_sent_error_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled per Source",
   "type": "timeseries",
   "description": "Number of schema reconciled per source",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (source) (rate(mir_schemastore_schema_reconciled_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "sum by (source) (rate(mir_schemastore_schema_reconciled_error_total{job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Event Capture Total",
   "type": "timeseries",
   "description": "Total of event capture per event type",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (event) (mir_eventstore_event_capture_total{job=\"${job}\"})",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Nats Clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(nats_varz_connections)", "legendFormat": "Connections" },
    { "expr": "sum(nats_varz_subscriptions)", "legendFormat": "Subscriptions" },
    { "expr": "sum(nats_varz_slow_consumers)", "legendFormat": "Slow consumer" }
   ]
  },
  {
   "title": "Nats Bytes",
   "type": "timeseries",
   "description": "Bytes in and out of Nats",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_bytes{job=\"${nats}\"}[$__rate_interval]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(rate(nats_varz_out_bytes{job=\"${nats}\"}[$__rate_interval]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "NATS Msgs",
   "type": "timeseries",
   "description": "Messages coming in and out of Nats bus",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_msgs{job=\"${nats}\"}[$__rate_interval]))",
     "legendFormat": "Msg In"
    },
    {
     "expr": "sum(rate(nats_varz_out_msgs{job=\"${nats}\"}[$__rate_interval]))",
     "legendFormat": "Msg out"
    }
   ]
  },
  {
   "title": "TimeseriesDB Writer Points",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "p/sec" } },
   "targets": [
    {
     "expr": "rate(storage_writer_ok_points_sum{job=\"${influx}\"}[$__rate_interval])",
     "legendFormat": "OK Points"
    },
    {
     "expr": "rate(storage_writer_dropped_points_sum{job=\"${influx}\"}[$__rate_interval])",
     "legendFormat": "Dropped Points"
    },
    {
     "expr": "rate(storage_writer_err_points_sum{job=\"${influx}\"}[$__rate_interval])",
     "legendFormat": "Error Points"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Number of Device Request",
   "type": "timeseries",
   "description": "Number of API device request per route",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_core_request_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "device {{route}}"
    },
    {
     "expr": "rate(mir_cfg_request_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "config {{route}}"
    },
    {
     "expr": "rate(mir_tlm_request_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "telemetry {{route}}"
    },
    {
     "expr": "rate(mir_cmd_request_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "commands {{route}}"
    }
   ]
  },
  {
   "title": "Number of Device Request Errors",
   "type": "timeseries",
   "description": "Number of API device request in errors per route",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_core_request_error_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "device {{route}}"
    },
    {
     "expr": "rate(mir_cfg_request_error_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "config {{route}}"
    },
    {
     "expr": "rate(mir_tlm_request_error_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "telemetry {{route}}"
    },
    {
     "expr": "rate(mir_cmd_request_error_total{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "command {{route}}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"node-expoter\"}) by (cpu)))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"node-exporter\"}) by (cpu)))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemFree_bytes{job=\"node-exporter\"} - (node_memory_Cached_bytes{job=\"node-exporter\"} + node_memory_Buffers_bytes{job=\"node-exporter\"} + node_memory_SReclaimable_bytes{job=\"node-exporter\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"${job}\"} + node_memory_SReclaimable_bytes{job=\"$job\",job=\"node-exporter\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"node-exporter\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{job=\"node-exporter\"} - node_memory_SwapFree_bytes{job=\"node-exporter\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\"}[$__rate_interval])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\"}[$__rate_interval])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"} | cmd = `mir`"
    }
   ]
  }
 ]
}