{
 "title": "Prometheus",
 "tags": [
  "mir",
  "mir-infra",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(prometheus_build_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Samples Appended",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=\"$job\"}[5m]))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$job\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "WAL Corruptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_corruptions_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=\"$job\"})",
     "legendFormat": "active_appenders"
    },
    {
     "expr": "sum(process_open_fds{job=\"$job\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"$job\"}",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"$job\"}",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{job=\"$job\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"$job\"}[5m])",
     "legendFormat": "collections"
    }
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=\"$job\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=\"$job\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=\"$job\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"$job\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"$job\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"$job\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{job=\"$job\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"$job\"}[5m])",
     "legendFormat": "missed"
    },
    {
     "expr": "rate(prometheus_rule_group_iterations_total{job=\"$job\"}[5m])",
     "legendFormat": "iterations"
    }
   ]
  }
 ]
}