apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
  - name: QuestDB
    typeName: PostgreSQL
    type: grafana-postgresql-datasource
    typeLogoUrl: "/public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg"
    access: proxy
    url: localhost:8812
    user: admin
    database: ""
    secureJsonData:
      password: "quest"
    jsonData:
      connMaxLifetime: 14400
      database: qdb
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1230
      sslmode: disable
