services:
  surrealdb:
    image: surrealdb/surrealdb:v2.3.7 # Last release of surrealdb before v2
    ports:
      - "8000:8000"
    volumes:
      - surrealdb_data:/var/lib/surrealdb
    user: root
    command:
      - start
      - surrealkv:/var/lib/surrealdb/mydatabase.db
      - --user
      - root
      - --pass
      - root
      - -A
      #- --log
      #- trace

volumes:
  surrealdb_data:
