services:
  surrealdb:
    image: surrealdb/surrealdb:v3.0.1
    ports:
      - "8000:8000"
    volumes:
      - surrealdb_data:/var/lib/surrealdb
    user: root
    restart: unless-stopped
    command:
      - start
      - surrealkv:/var/lib/surrealdb/mydatabase.db
      - --user
      - root
      - --pass
      - root
      - -A
      - --log
      - debug
    environment:
      # To remove when fix in future release
      # https://github.com/surrealdb/surrealdb/issues/7038
      - SURREAL_PLANNER_STRATEGY=compute-only

volumes:
  surrealdb_data:
