# mir tools security generate-creds mir_srv -p ./mir_srv.creds
# kubectl create secret generic mir-auth-secret --from-file=mir.creds=mir_srv.creds --dry-run=client -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: mir-auth-secret
data:
  mir.creds: <base64>
