# mir tools security generate-resolver  -p ./resolver.conf
# kubectl create secret generic mir-resolver-secret --from-file=resolver.conf --dry-run=client -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: mir-resolver-secret
data:
  resolver.conf: <base64>
