{
 "title": "Command",
 "tags": [
  "mir",
  "mir-module",
  "mir-cmd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mir_app_info{name=~\"protocmd|mir\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mir_app_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_health_alive{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Live Objects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"$instance\"} - go_memstats_frees_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_health_ready{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Command", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Commands sent to Devices",
   "type": "timeseries",
   "description": "Number of commands sent to devices",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cmd_device_cmd_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(mir_cmd_device_cmd_sent_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Number of Command Request",
   "type": "timeseries",
   "description": "Number of API command request per route",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cmd_request_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Number of Command Request in Error",
   "type": "timeseries",
   "description": "Number of API command request in error per route",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cmd_request_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Schema in Cache",
   "type": "stat",
   "description": "Number of device schema in cache",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_schemastore_schema_cache_count{instance=\"$instance\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Total Number of Schema Reconciled per Source",
   "type": "stat",
   "description": "Number of schema reconciled per source",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_schemastore_schema_reconciled_total{instance=\"$instance\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled per Source",
   "type": "timeseries",
   "description": "Rate of schema reconciled per source",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_schemastore_schema_reconciled_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled Error",
   "type": "timeseries",
   "description": "Rate of schema reconciled error",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_schemastore_schema_reconciled_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "error"
    }
   ]
  }
 ]
}