{
 "title": "Configuration",
 "tags": [
  "mir",
  "mir-module",
  "mir-cfg"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mir_app_info{name=~\"mir|protocfg\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mir_app_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mir_health_alive{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Live Objects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"$instance\"} - go_memstats_frees_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mir_health_ready{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Desired Properties Sent to Devices",
   "type": "timeseries",
   "description": "Number of desired properties sent to devices",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_cfg_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "user requested"
    },
    {
     "expr": "rate(mir_cfg_device_desired_props_request_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "device requested"
    }
   ]
  },
  {
   "title": "Reported Properties from Devices",
   "type": "timeseries",
   "description": "Total number of reported properties from devices",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_reported_props_request_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "reported properties"
    }
   ]
  },
  {
   "title": "Number of Config Request",
   "type": "timeseries",
   "description": "Number of API config request per route",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_request_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Desired Properties Sent to Devices in Error",
   "type": "timeseries",
   "description": "Number of desired properties sent to devices in error",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_cfg_sent_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "user requested"
    },
    {
     "expr": "rate(mir_cfg_device_desired_props_request_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "device requested"
    }
   ]
  },
  {
   "title": "Reported Properties from Devices in Error",
   "type": "timeseries",
   "description": "Total number of reported properties from devices in error",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_reported_props_request_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "reported properties"
    }
   ]
  },
  {
   "title": "Number of Config Request in Error",
   "type": "timeseries",
   "description": "Number of API config request in error per route",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_request_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Schema in Cache",
   "type": "stat",
   "description": "Number of device schema in cache",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_schemastore_schema_cache_count{instance=\"$instance\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Total Number of Schema Reconciled per Source",
   "type": "stat",
   "description": "Number of schema reconciled per source",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_schemastore_schema_reconciled_total{instance=\"$instance\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled per Source",
   "type": "timeseries",
   "description": "Rate of schema reconciled per source",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_schemastore_schema_reconciled_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled Error",
   "type": "timeseries",
   "description": "Rate of schema reconciled error",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_schemastore_schema_reconciled_error_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{system=\"mir\", compose_service=\"mir\"} | cmd = `protocfg` or srv = `protocfg_server`"
    }
   ]
  }
 ]
}