{
 "title": "Mir Module",
 "tags": [
  "mir",
  "mir-module",
  "mir-cfg"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mir_app_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mir_health_alive{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Device Online",
   "type": "stat",
   "description": "Number of online devices",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_core_device_status_count{status=\"online\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Schema in Cache",
   "type": "stat",
   "description": "Number of device schema in cache",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mir_schemastore_schema_cache_count{})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Number of Schema Reconciled per Source",
   "type": "stat",
   "description": "Number of schema reconciled per source",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source) (mir_schemastore_schema_reconciled_total{})",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mir_health_ready{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Device Offline",
   "type": "stat",
   "description": "Number of offline devices",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_core_device_status_count{status=\"offline\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Telemetry Ingesters in Cache",
   "type": "stat",
   "description": "Number of telemetry ingesters in cache",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mir_tlm_timeseries_ingesters_count{}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_memstats_sys_bytes{})" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_goroutines{})" }
   ]
  },
  {
   "title": "Live Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mallocs_total{}-go_memstats_frees_total{})"
    }
   ]
  },
  { "title": "Mir", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Telemetry Points from Devices",
   "type": "timeseries",
   "description": "Number of telemetry points sent from devices",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_tlm_datapoint_count{}[$__rate_interval])",
     "legendFormat": "points"
    }
   ]
  },
  {
   "title": "Commands Sent to Devices",
   "type": "timeseries",
   "description": "Number of commands sent to devices",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cmd_device_cmd_sent_total{}[$__rate_interval])",
     "legendFormat": "commands"
    }
   ]
  },
  {
   "title": "Telemetry Points from Devices in Error",
   "type": "timeseries",
   "description": "Number of telemetry points sent from devices in error",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_tlm_datapoint_error_count{}[$__rate_interval])",
     "legendFormat": "points"
    }
   ]
  },
  {
   "title": "Commands Sent to Devices in Error",
   "type": "timeseries",
   "description": "Number of commands sent to devices in error",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cmd_device_cmd_sent_error_total{}[$__rate_interval])",
     "legendFormat": "commands"
    }
   ]
  },
  {
   "title": "Properties Sent to/from Devices",
   "type": "timeseries",
   "description": "Number of desired and reported properties sent to/from devices",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_cfg_sent_total{}[$__rate_interval])",
     "legendFormat": "desired properties user requested"
    },
    {
     "expr": "rate(mir_cfg_device_desired_props_request_total{}[$__rate_interval])",
     "legendFormat": "desired properties device requested"
    },
    {
     "expr": "rate(mir_cfg_device_reported_props_request_total{}[$__rate_interval])",
     "legendFormat": "reported properties"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled per Source",
   "type": "timeseries",
   "description": "Rate of schema reconciled per source",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (source) (rate(mir_schemastore_schema_reconciled_total{}[$__rate_interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Properties Sent to/fom Devices in Error",
   "type": "timeseries",
   "description": "Number of desired and reported properties sent to/from devices in error",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mir_cfg_device_cfg_sent_error_total{}[$__rate_interval])",
     "legendFormat": "desired properties user requested"
    },
    {
     "expr": "rate(mir_cfg_device_desired_props_request_error_total{}[$__rate_interval])",
     "legendFormat": "desired properties device requested"
    },
    {
     "expr": "rate(mir_cfg_device_reported_props_request_error_total{}[$__rate_interval])",
     "legendFormat": "reported properties"
    }
   ]
  },
  {
   "title": "Rate of Schema Reconciled Error",
   "type": "timeseries",
   "description": "Rate of schema reconciled error",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (source) (rate(mir_schemastore_schema_reconciled_error_total{}[$__rate_interval]))",
     "legendFormat": "schema reconciled"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Device Request",
     "type": "timeseries",
     "description": "Number of API device request per route",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_core_request_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Config Request",
     "type": "timeseries",
     "description": "Number of API config request per route",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_cfg_request_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Device Request Errors",
     "type": "timeseries",
     "description": "Number of API device request in errors per route",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_core_request_error_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Config Request in Error",
     "type": "timeseries",
     "description": "Number of API config request in error per route",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_cfg_request_error_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Command Request",
     "type": "timeseries",
     "description": "Number of API command request per route",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_cmd_request_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Telemetry Request",
     "type": "timeseries",
     "description": "Number of API telemetry request per route",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_tlm_request_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Command Request in Error",
     "type": "timeseries",
     "description": "Number of API command request in error per route",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_cmd_request_error_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Number of Telemetry Request in Error",
     "type": "timeseries",
     "description": "Number of API telemetry request in error per route",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(mir_tlm_request_error_total{}[$__rate_interval])",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  }
 ]
}