apiVersion: k3d.io/v1alpha5
kind: Simple
#name: mir-local-dev
servers: 1
agents: 3
options:
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
ports:
  # Traefik
  - port: 8081:80
    nodeFilters:
      - loadbalancer
  # Nats
  - port: 31422:31422
    nodeFilters:
      - loadbalancer
  - port: 31922:31922
    nodeFilters:
      - loadbalancer
registries:
  config: |
    configs:
      "ghcr.io":
        auth:
          username: <user>
          password: <token>
