apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mir.fullname" . }}-config
  labels:
    {{- include "mir.labels" . | nindent 4 }}
data:
  mir.yaml: |
    mir:
      {{- if .Values.nats.enabled }}
      url: "nats://{{ include "mir.fullname" . }}-nats:4222"
      {{- else }}
      url: {{ .Values.config.mir.url | quote }}
      {{- end }}
      logLevel: {{ .Values.config.mir.logLevel | quote }}
      httpPort: {{ .Values.service.targetPort }}
    surreal:
      {{- if .Values.surrealdb.enabled }}
      url: "ws://{{ include "mir.fullname" . }}-surrealdb:{{ .Values.surrealdb.service.port }}/rpc"
      {{- else }}
      url: {{ .Values.config.surreal.url | quote }}
      {{- end }}
      user: {{ .Values.config.surreal.user | quote }}
      password: {{ .Values.config.surreal.password | quote }}
      namespace: {{ .Values.config.surreal.namespace | quote }}
      database: {{ .Values.config.surreal.database | quote }}
    influx:
      {{- if .Values.influxdb2.enabled }}
      url: "http://{{ include "mir.fullname" . }}-influxdb2:{{ .Values.influxdb2.service.port }}"
      {{- else }}
      url: {{ .Values.config.influx.url | quote }}
      {{- end }}
      token: {{ .Values.config.influx.token | quote }}
      org: {{ .Values.config.influx.org | quote }}
      bucket: {{ .Values.config.influx.bucket | quote }}
      batchSize: {{ .Values.config.influx.batchSize }}
      flushInterval: {{ .Values.config.influx.flushInterval }}
      retryBufferLimit: {{ .Values.config.influx.retryBufferLimit }}
      gzip: {{ .Values.config.influx.gzip }}
