{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mir.fullname" . }}
  labels:
    {{- include "mir.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mir.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mir.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - mir
            - serve
            - --server-config
            - /etc/mir/mir.yaml
          env:
            - name: GO_PPROF
              value: "on"
            {{- with .Values.envVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.secretRef }}
            - secretRef:
                name: {{ . }}
                optional: true
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- $scheme := .Values.mirHttpTlsSecretRef | empty | ternary "HTTP" "HTTPS" }}
          {{- with .Values.livenessProbe }}
          {{- $probe := deepCopy . }}
          {{- $_ := set $probe.httpGet "scheme" $scheme }}
          livenessProbe:
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          {{- $probe := deepCopy . }}
          {{- $_ := set $probe.httpGet "scheme" $scheme }}
          readinessProbe:
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/mir/mir.yaml
              subPath: mir.yaml
              readOnly: true
            - name: contexts
              mountPath: /etc/mir/cli.yaml
              subPath: cli.yaml
              readOnly: true
            {{- with .Values.authSecretRef }}
            - name: auth
              mountPath: /etc/mir/mir.creds
              subPath: mir.creds
              readOnly: true
            {{- end }}
            {{- with .Values.mirHttpTlsSecretRef }}
            - name: mir-http-tls
              mountPath: /etc/mir/http-tls/tls.crt
              subPath: tls.crt
              readOnly: true
            - name: mir-http-tls
              mountPath: /etc/mir/http-tls/tls.key
              subPath: tls.key
              readOnly: true
            {{- end }}
            {{- if .Values.caSecretRef }}
            - name: mir-certs
              mountPath: /etc/mir/ca.crt
              subPath: ca.crt
              readOnly: true
            {{- end }}
            {{- if .Values.tlsSecretRef }}
            - name: mir-certs
              mountPath: /etc/mir/tls.crt
              subPath: tls.crt
              readOnly: true
            - name: mir-certs
              mountPath: /etc/mir/tls.key
              subPath: tls.key
              readOnly: true
            {{- end }}
            {{- range .Values.config.contexts }}
            {{- if .sec.credsSecretRef }}
            - name: {{ printf "ctx-creds-%s" (.name | lower | replace "." "-" | replace "_" "-") }}
              mountPath: {{ printf "/etc/mir/creds/%s.creds" .name }}
              subPath: {{ default "mir.creds" .sec.credsSecretKey }}
              readOnly: true
            {{- end }}
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "mir.fullname" . }}-config
        - name: contexts
          configMap:
            name: {{ include "mir.fullname" . }}-config
        {{- with .Values.authSecretRef }}
        - name: auth
          secret:
            secretName: {{ . }}
        {{- end }}
        {{- with .Values.mirHttpTlsSecretRef }}
        - name: mir-http-tls
          secret:
            secretName: {{ . }}
        {{- end }}
        {{- if or .Values.caSecretRef .Values.tlsSecretRef }}
        - name: mir-certs
          projected:
            sources:
            {{- with .Values.caSecretRef }}
            - secret:
                name: {{ . }}
                items:
                - key: ca.crt
                  path: ca.crt
            {{- end }}
            {{- with .Values.tlsSecretRef }}
            - secret:
                name: {{ . }}
                items:
                - key: tls.crt
                  path: tls.crt
                - key: tls.key
                  path: tls.key
            {{- end }}
        {{- end }}
        {{- range .Values.config.contexts }}
        {{- if .sec.credsSecretRef }}
        - name: {{ printf "ctx-creds-%s" (.name | lower | replace "." "-" | replace "_" "-") }}
          secret:
            secretName: {{ .sec.credsSecretRef }}
        {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
