services:
  surrealdb:
    image: surrealdb/surrealdb:v1.5.4 # Last release of surrealdb before v2
    ports:
      - "8000:8000"
    volumes:
      - surrealdb-data:/var/lib/surrealdb
    user: root
    command:
      - start
      - file:/var/lib/surrealdb/mydatabase.db
      - --user
      - root
      - --pass
      - root
      - -A
      #- --log
      #- trace

volumes:
  surrealdb-data:
