image:
  tag: "v2.3.7"
surrealdb:
  path: "surrealkv:/data/mir.db"  # File-based storage
  initial_user: "root"
  initial_pass: "root"
  log: debug
persistence:
  enabled: true
  size: 10Gi
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: surreal-local
      paths:
        - path: /
          pathType: Prefix
  tls: []
