{{- if and .Values.surrealdb.enabled .Values.surrealdb.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mir.fullname" . }}-surrealdb-data
  labels:
    {{- include "mir.labels" . | nindent 4 }}
    app.kubernetes.io/component: surrealdb
spec:
  accessModes:
    - {{ .Values.surrealdb.persistence.accessMode }}
  {{- if .Values.surrealdb.persistence.storageClass }}
  storageClassName: {{ .Values.surrealdb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.surrealdb.persistence.size }}
{{- end }}