config:
  mir:
    logLevel: "debug"

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: mir-local
      paths:
        - path: /
          pathType: Prefix

nats:
  enabled: true
  ingress:
    enabled: true
    className: "traefik"
    annotations: {}
    host: nats-local
    path: /
    pathType: Prefix
  service:
    merge:
      spec:
        type: LoadBalancer
        ports:
          - appProtocol: tcp
            name: nats
            nodePort: 31422
            port: 4222
            protocol: TCP
            targetPort: nats

surrealdb:
  enabled: true
  ingress:
    enabled: true
    className: "traefik"
    annotations: {}
    host: surreal-local
    path: /*
    pathType: Prefix
  # Override the PVC name to match the release name
  # This assumes you're installing with: helm install mir ...
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mir-test-surrealdb-data
  volumeMounts:
    - name: data
      mountPath: /data
