config:
  mir:
    logLevel: "debug"

ingress:
  enabled: false

nats:
  enabled: true
  service:
    merge:
      spec:
        type: LoadBalancer
        ports:
          - appProtocol: tcp
            name: nats
            nodePort: 31423
            port: 4222
            protocol: TCP
            targetPort: nats

surrealdb:
  enabled: true

influxdb2:
  enabled: true

kube-prometheus-stack:
  enabled: false
