## Quick Setup
# 1. NATS TLS Secret
# kubectl create secret tls <NATS_TLS_SECRET> --cert=tls.crt --key=tls.key
# 2. NATS CA Secret (Mutual TLS)
# kubectl create secret generic <NATS_CA_SECRET> --from-file=ca.crt=ca.crt
# 3. Mir CA Secret
# kubectl create secret generic <MIR_CA_SECRET> --from-file=ca.crt=ca.crt
# 4. Mir TLS Secret (Mutual TLS)
# kubectl create secret tls <MIR_TLS_SECRET> --cert=tls.crt --key=tls.key
##

## NATS
nats:
  config:
    nats:
      tls:
        enabled: true
        secretName: <NATS_TLS_SECRET>
        dir: /etc/nats-certs
        cert: tls.crt
        key: tls.key
        merge:
          verify: true # True for Mutual TLS, false for ServerOnly TLS
          timeout: 2
  # Reference CA for mTLS
  tlsCA:
    enabled: true
    secretName: <NATS_CA_SECRET>
    dir: /etc/nats-ca-certs
    key: ca.crt

## MIR
# Configure Mir Server Access, see
# - ./secret/mir-ca.secret.yaml
# - ./secret/mir-tls.secret.yaml
caSecretRef: <MIR_CA_SECRET>
tlsSecretRef: <MIR_TLS_SECRET>
