global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - "/etc/prometheus/alertrules/*.yml"
  - "/etc/prometheus/alertrules/*.yaml"

scrape_configs:
  # INFRA
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3000"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:9093"]
  - job_name: "influxdb"
    static_configs:
      - targets: ["localhost:8086"]
  - job_name: "loki"
    static_configs:
      - targets: ["localhost:3100"]
  - job_name: "promtail"
    static_configs:
      - targets: ["localhost:9080"]
  - job_name: "nats"
    static_configs:
      - targets: ["localhost:7777"]
  # MIR
  - job_name: "mir"
    static_configs:
      - targets: ["localhost:3015"]
  - job_name: "core"
    static_configs:
      - targets: ["localhost:3016"]
  - job_name: "tlm"
    static_configs:
      - targets: ["localhost:3017"]
  - job_name: "cmd"
    static_configs:
      - targets: ["localhost:3018"]
  - job_name: "cfg"
    static_configs:
      - targets: ["localhost:3019"]
  - job_name: "eventstore"
    static_configs:
      - targets: ["localhost:3020"]
