// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: v1alpha/device_api/device.proto

package device_api

import (
	common_api "github.com/maxthom/mir/pkgs/api/proto/v1alpha/common_api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Send a request to create a new device in the system
type SchemaRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SchemaRetrieveRequest) Reset() {
	*x = SchemaRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha_device_api_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRetrieveRequest) ProtoMessage() {}

func (x *SchemaRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha_device_api_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRetrieveRequest.ProtoReflect.Descriptor instead.
func (*SchemaRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha_device_api_device_proto_rawDescGZIP(), []int{0}
}

// Response to the create device request
// Only the error or the response data will be set
type SchemaRetrieveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*SchemaRetrieveResponse_Schema
	//	*SchemaRetrieveResponse_Error
	Response isSchemaRetrieveResponse_Response `protobuf_oneof:"response"`
}

func (x *SchemaRetrieveResponse) Reset() {
	*x = SchemaRetrieveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha_device_api_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRetrieveResponse) ProtoMessage() {}

func (x *SchemaRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha_device_api_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRetrieveResponse.ProtoReflect.Descriptor instead.
func (*SchemaRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha_device_api_device_proto_rawDescGZIP(), []int{1}
}

func (m *SchemaRetrieveResponse) GetResponse() isSchemaRetrieveResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *SchemaRetrieveResponse) GetSchema() []byte {
	if x, ok := x.GetResponse().(*SchemaRetrieveResponse_Schema); ok {
		return x.Schema
	}
	return nil
}

func (x *SchemaRetrieveResponse) GetError() *common_api.Error {
	if x, ok := x.GetResponse().(*SchemaRetrieveResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isSchemaRetrieveResponse_Response interface {
	isSchemaRetrieveResponse_Response()
}

type SchemaRetrieveResponse_Schema struct {
	Schema []byte `protobuf:"bytes,1,opt,name=schema,proto3,oneof"` // Schema in bytes
}

type SchemaRetrieveResponse_Error struct {
	Error *common_api.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // HTTP like error if something went wrong
}

func (*SchemaRetrieveResponse_Schema) isSchemaRetrieveResponse_Response() {}

func (*SchemaRetrieveResponse_Error) isSchemaRetrieveResponse_Response() {}

var File_v1alpha_device_api_device_proto protoreflect.FileDescriptor

var file_v1alpha_device_api_device_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x1a, 0x1f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6d, 0x0a, 0x16, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12,
	0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xb4, 0x01, 0x0a, 0x12, 0x63,
	0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x42, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x78,
	0x74, 0x68, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0xa2, 0x02, 0x03, 0x56, 0x44, 0x58,
	0xaa, 0x02, 0x0e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0xca, 0x02, 0x0e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x5c, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0xe2, 0x02, 0x1a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x5c, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0f, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x3a, 0x3a, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha_device_api_device_proto_rawDescOnce sync.Once
	file_v1alpha_device_api_device_proto_rawDescData = file_v1alpha_device_api_device_proto_rawDesc
)

func file_v1alpha_device_api_device_proto_rawDescGZIP() []byte {
	file_v1alpha_device_api_device_proto_rawDescOnce.Do(func() {
		file_v1alpha_device_api_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha_device_api_device_proto_rawDescData)
	})
	return file_v1alpha_device_api_device_proto_rawDescData
}

var file_v1alpha_device_api_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1alpha_device_api_device_proto_goTypes = []interface{}{
	(*SchemaRetrieveRequest)(nil),  // 0: v1alpha.device.SchemaRetrieveRequest
	(*SchemaRetrieveResponse)(nil), // 1: v1alpha.device.SchemaRetrieveResponse
	(*common_api.Error)(nil),       // 2: v1alpha.common.Error
}
var file_v1alpha_device_api_device_proto_depIdxs = []int32{
	2, // 0: v1alpha.device.SchemaRetrieveResponse.error:type_name -> v1alpha.common.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1alpha_device_api_device_proto_init() }
func file_v1alpha_device_api_device_proto_init() {
	if File_v1alpha_device_api_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1alpha_device_api_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchemaRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha_device_api_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchemaRetrieveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1alpha_device_api_device_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SchemaRetrieveResponse_Schema)(nil),
		(*SchemaRetrieveResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha_device_api_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha_device_api_device_proto_goTypes,
		DependencyIndexes: file_v1alpha_device_api_device_proto_depIdxs,
		MessageInfos:      file_v1alpha_device_api_device_proto_msgTypes,
	}.Build()
	File_v1alpha_device_api_device_proto = out.File
	file_v1alpha_device_api_device_proto_rawDesc = nil
	file_v1alpha_device_api_device_proto_goTypes = nil
	file_v1alpha_device_api_device_proto_depIdxs = nil
}
