{
 "title": "Mir Infra",
 "tags": [
  "mir",
  "mir-infra",
  "mir-infra-overall"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Silenced Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Nats Connections",
   "type": "stat",
   "description": "Number of activate connections to Nats Server",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnatsd_varz_connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "NATS Msgs",
   "type": "stat",
   "description": "Message rates per second in and out of Nats",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gnatsd_varz_in_msgs{job=\"natsio\"}[$__rate_interval])+rate(gnatsd_varz_out_msgs{job=\"natsio\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Telemetry Points",
   "type": "stat",
   "description": "Number of datapoints ingesting to TimeseriesDB",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(storage_writer_ok_points_sum{job=\"influxdb\"}[$__rate_interval])+rate(storage_writer_dropped_points_sum{job=\"influxdb\"}[$__rate_interval])+rate(storage_writer_err_points_sum{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "OK Points"
    }
   ]
  },
  {
   "title": "Telemetry HTTP Request",
   "type": "stat",
   "description": "Number of Telemetry HTTP request to TimeseriesDB",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_api_requests_total{job=\"influxdb\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"node\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"node\"})) * 100"
    }
   ]
  },
  { "title": "Nats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "NATS Msgs In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(gnatsd_varz_in_msgs{job=\"natsio\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(gnatsd_varz_out_msgs{job=\"natsio\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(gnatsd_varz_in_bytes{job=\"natsio\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(gnatsd_varz_out_bytes{job=\"natsio\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_subscriptions", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gnatsd_varz_slow_consumers", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "TimeseriesDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Storage Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(boltdb_reads_total{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(boltdb_writes_total{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage Writer Points",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(storage_writer_dropped_points_sum{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "Dropped Points"
    },
    {
     "expr": "rate(storage_writer_err_points_sum{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "Error Points"
    },
    {
     "expr": "rate(storage_writer_ok_points_sum{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "OK Points"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_api_requests_total{job=\"influxdb\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_api_request_duration_seconds_bucket{job=\"influxdb\"}[$__rate_interval])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_api_request_duration_seconds_bucket{job=\"influxdb\"}[$__rate_interval])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}} (p50)"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{job=\"prometheus\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "timeseries",
   "description": "Number of alerts by state such as `active`, `suppressed` etc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Received Alerts",
   "type": "timeseries",
   "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total[$__interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"node\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"node\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"node\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"node\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"node\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"node\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"node\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"node\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"node\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"node\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}