[book]
authors = ["maxthom"]
language = "en"
multilingual = false
src = "src"
title = "Mir"
description = "A book about the Mir IotHub ecosystem"

[output.html]
git-repository-url = "https://github.com/maxthom/mir"
additional-css = ["theme/css/custom.css"]
