package main

import (
	"context"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/maxthom/mir/internal/libs/boiler/mir_config"
	"github.com/maxthom/mir/internal/libs/boiler/mir_log"
	"github.com/maxthom/mir/internal/libs/build_meta"
	bus "github.com/maxthom/mir/internal/libs/external/natsio"
	"github.com/maxthom/mir/internal/ui"
	"github.com/maxthom/mir/internal/ui/cli"
	"github.com/maxthom/mir/internal/ui/tui"
	"github.com/maxthom/mir/pkgs/module/mir"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

var l zerolog.Logger
var msgBus *bus.BusConn
var ctx context.Context

type configFlag string

type (
	Globals struct {
		Debug      bool        `short:"D" help:"Enable debug mode"`
		Ctx        string      `help:"Set context to use. Use mir context for list."`
		LogLevel   string      `short:"L" help:"Set the logging level (debug|info|warn|error|fatal). default:info"`
		ConfigFile configFlag  `short:"C" help:"Set path for config path. default:~/.config/mir/cli.yaml"`
		Version    VersionFlag `short:"V" name:"version" help:"Print version information and quit"`
	}
	CLI struct {
		Globals

		Client  Client         `cmd:"" embed:"" help:"Test Mir ecosystem of servers and services"`
		Serve   cli.ServeCmd   `cmd:"" help:"Serve Mir ecosystem of servers and services"`
		Infra   cli.InfraCmd   `cmd:"" help:"Start and stop Mir supporting infrastructure"`
		Context cli.ContextCmd `cmd:"" aliases:"ctx" help:"Set and list contexts"`
		Tools   cli.ToolsCmd   `cmd:"" aliases:"" help:"Various tools to interact with Mir ecosystem"`
	}
	// Each commands that requires Mir connected as client
	// Add command to BeforeApply to have a connection
	Client struct {
		Tui    tui.Cmd       `cmd:"" help:"Open Mir in TUI mode" default:"withargs" hidden:""`
		Device cli.DeviceCmd `cmd:"" aliases:"dev" help:"Manage fleet of Mir devices"`
		Event  cli.EventCmd  `cmd:"" aliases:"evt" help:"Explore list of events generated by Mir"`
		Swarm  cli.SwarmCmd  `cmd:"" help:"Create virtual devices to mimic workload for test or demo purposes"`
	}
	VersionFlag string
)

const (
	AppName = "mir"
)

func (v VersionFlag) Decode(ctx *kong.DecodeContext) error { return nil }
func (v VersionFlag) IsBool() bool                         { return true }
func (v VersionFlag) BeforeApply(app *kong.Kong, vars kong.Vars) error {
	fmt.Println(vars["version"])
	app.Exit(0)
	return nil
}

func main() {
	var c CLI
	var logFile *os.File
	defer logFile.Close()

	// CLI
	kongCtx := kong.Parse(&c,
		kong.Name("mir"),
		kong.Description("A command line and terminal user interface to operate the Mir ecosystem 🛰️"),
		kong.UsageOnError(),
		kong.ConfigureHelp(kong.HelpOptions{
			Compact:             true,
			Tree:                false,
			NoExpandSubcommands: true,
		}),
		kong.Vars{
			"version": build_meta.GetLongVersion(),
		},
		kong.Bind(logFile),
	)

	err := kongCtx.Run()
	if err != nil {
		log.Error().Err(err).Msg("")
		fmt.Println(err)
	}
}

func (d *CLI) BeforeApply(k *kong.Context, logFile *os.File) error {

	// Config
	cfg := ui.NewDefaultConfig()
	errCfg, lookupFiles, foundFiles := mir_config.New(AppName,
		mir_config.WithEtcFilePath("mir/cli.yaml", mir_config.Yaml, false),
		mir_config.WithXdgConfigHomeFilePath("mir/cli.yaml", mir_config.Yaml, false),
		mir_config.WithFilePath(string(d.ConfigFile), mir_config.Yaml, false),
		mir_config.WithEnvVars("MIR"),
	).LoadAndUnmarshal(&cfg)
	if errCfg != nil {
		return errCfg
	}
	if len(foundFiles) > 0 {
		ui.LoadedConfigPath = foundFiles[len(foundFiles)-1]
	}
	k.Bind(cfg)

	if d.LogLevel != "" {
		cfg.LogLevel = d.LogLevel
	}

	if d.Ctx != "" {
		cfg.CurrentContext = d.Ctx
	}
	ctx, ok := cfg.GetCurrentContext()
	if !ok {
		if !slices.Contains(k.Args, "context") && !slices.Contains(k.Args, "ctx") {
			return fmt.Errorf("current context '%s' does not exist.\nRun 'mir context' to list available contexts.", cfg.CurrentContext)
		}
	}
	k.Bind(ctx)

	log := mir_log.Setup(
		mir_log.WithFlagAndFileLogLevel(d.Debug, cfg.LogLevel, &d.LogLevel),
		mir_log.WithTimeFormatUnix(),
		mir_log.WithXdgConfigHomeLogFile("mir/cli.log", logFile),
		mir_log.WithAppName(AppName),
	)

	log.Info().Strs("lookup config", lookupFiles).Strs("found config", foundFiles).Msg("configuration loaded")
	prettyCfg, err := mir_config.JsonMarshalWithoutSecrets(cfg)
	if err != nil {
		log.Error().Err(err).Msg("error marshalling config")
		os.Exit(1)
	}
	log.Info().Str("config", string(prettyCfg)).Msg("")
	k.Bind(log)

	return nil
}

// There is no hook for after subcommands are executed
// Therefor each command must close Mir :(
func (d *Client) BeforeApply(k *kong.Context, log zerolog.Logger, ctx ui.Context) error {
	// Normally, this hook should not be called if command not in Client struct
	// Add command requiring Client in this list until fix
	// https://github.com/alecthomas/kong/issues/549
	clientCmds := []string{"tui", "device", "dev", "swarm", "event", "evt"}
	cmdNodes := strings.Split(k.Command(), " ")
	if len(cmdNodes) == 0 {
		return nil
	}
	rootCmd := cmdNodes[0]
	if !slices.Contains(clientCmds, rootCmd) {
		return nil
	}

	opts := append(mir.WithDefaultReconnectOpts(), mir.WithDefaultConnectionLogging(log)...)
	opts = append(opts, mir.WithUserCredentials(ctx.Credentials))
	opts = append(opts, mir.WithRootCA(ctx.RootCA))
	opts = append(opts, mir.WithClientCertificate(ctx.TlsCert, ctx.TlsKey))
	m, err := mir.Connect(AppName, ctx.Target, opts...)
	if err != nil {
		log.Err(err).Msg("error connection to Mir server")
		fmt.Printf("error connecting to Mir server: %v\n", err)
		os.Exit(1)
	}
	log.Info().Str("url", ctx.Target).Str("status", m.Bus.Status().String()).Msg("msg bus status")
	k.Bind(m)

	return nil
}
