package main

import (
	"context"
	"fmt"
	"os"

	"github.com/alecthomas/kong"
	"github.com/maxthom/mir/internal/libs/boiler/mir_config"
	"github.com/maxthom/mir/internal/libs/boiler/mir_log"
	"github.com/maxthom/mir/internal/libs/build_meta"
	bus "github.com/maxthom/mir/internal/libs/external/natsio"
	"github.com/maxthom/mir/internal/ui/cli"
	"github.com/maxthom/mir/internal/ui/tui"
	"github.com/maxthom/mir/pkgs/module/mir"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

var l zerolog.Logger
var msgBus *bus.BusConn
var ctx context.Context

type configFlag string

type (
	config struct {
		LogLevel string
		Target   string
	}
	Globals struct {
		Target     string      `short:"T" help:"Mir connection target. default:nats://127.0.0.1:4222"`
		Debug      bool        `short:"D" help:"Enable debug mode"`
		LogLevel   string      `short:"L" help:"Set the logging level (debug|info|warn|error|fatal). default:info"`
		ConfigFile configFlag  `short:"C" help:"Set path for config path. default:~/.config/mir/cli.yaml"`
		Version    VersionFlag `short:"V" name:"version" help:"Print version information and quit"`
	}
	CLI struct {
		Client Client       `cmd:"" embed:"" help:"Test Mir ecosystem of servers and services"`
		Serve  cli.ServeCmd `cmd:"" help:"Serve Mir ecosystem of servers and services"`
		Infra  cli.InfraCmd `cmd:"" help:"Start and stop Mir supporting infrastructure"`
		Tools  cli.ToolsCmd `cmd:"" aliases:"" help:"Various tools to interact with Mir ecosystem"`
	}
	// Each commands that requires Mir connected as client
	Client struct {
		Globals

		Tui    tui.Cmd       `cmd:"" help:"Open Mir in TUI mode" default:"withargs" hidden:""`
		Device cli.DeviceCmd `cmd:"" aliases:"dev" help:"Manage fleet of Mir devices"`
		Event  cli.EventCmd  `cmd:"" aliases:"evt" help:"Explore list of events generated by Mir"`
		Swarm  cli.SwarmCmd  `cmd:"" help:"Create virtual devices to mimic workload for test or demo purposes"`
	}
	VersionFlag string
)

const (
	AppName = "mir"
)

var (
	defaultCfg = config{
		LogLevel: "info",
		Target:   "nats://127.0.0.1:4222",
	}
)

func (v VersionFlag) Decode(ctx *kong.DecodeContext) error { return nil }
func (v VersionFlag) IsBool() bool                         { return true }
func (v VersionFlag) BeforeApply(app *kong.Kong, vars kong.Vars) error {
	fmt.Println(vars["version"])
	app.Exit(0)
	return nil
}

func main() {
	var c CLI
	var logFile *os.File
	defer logFile.Close()

	// CLI
	kongCtx := kong.Parse(&c,
		kong.Name("mir"),
		kong.Description("A command line and terminal user interface to operate the Mir ecosystem 🛰️"),
		kong.UsageOnError(),
		kong.ConfigureHelp(kong.HelpOptions{
			Compact:             true,
			Tree:                false,
			NoExpandSubcommands: true,
		}),
		kong.Vars{
			"version": build_meta.GetLongVersion(),
		},
		kong.Bind(logFile),
	)

	err := kongCtx.Run()
	if err != nil {
		log.Error().Err(err).Msg("")
		fmt.Println(err)
	}
}

// There is no hook for after subcommands are executed
// Therefor each command must close Mir :(
func (d *Client) AfterApply(k *kong.Context, logFile *os.File) error {
	// Config
	cfg := defaultCfg
	errCfg, lookupFiles, foundFiles := mir_config.New(AppName,
		mir_config.WithEtcFilePath("mir/cli.yaml", mir_config.Yaml, false),
		mir_config.WithXdgConfigHomeFilePath("mir/cli.yaml", mir_config.Yaml, false),
		mir_config.WithFilePath(string(d.ConfigFile), mir_config.Yaml, false),
		mir_config.WithEnvVars("MIR"),
	).LoadAndUnmarshal(&cfg)

	if d.LogLevel != "" {
		cfg.LogLevel = d.LogLevel
	}
	if d.Target != "" {
		cfg.Target = d.Target
	}

	log := mir_log.Setup(
		mir_log.WithFlagAndFileLogLevel(d.Debug, cfg.LogLevel, &d.LogLevel),
		mir_log.WithTimeFormatUnix(),
		mir_log.WithXdgConfigHomeLogFile("mir/cli.log", logFile),
		mir_log.WithAppName(AppName),
	)

	log.Info().Strs("lookup config", lookupFiles).Strs("found config", foundFiles).Msg("configuration loaded")
	if errCfg != nil {
		log.Err(errCfg).Msg("error loading config")
		os.Exit(1)
	}
	prettyCfg, err := mir_config.JsonMarshalWithoutSecrets(cfg)
	if err != nil {
		log.Error().Err(err).Msg("error marshalling config")
		os.Exit(1)
	}
	log.Info().Str("config", string(prettyCfg)).Msg("")

	m, err := mir.Connect(AppName, cfg.Target, append(mir.WithDefaultReconnectOpts(), mir.WithDefaultConnectionLogging(log)...)...)
	if err != nil {
		log.Err(err).Msg("error connection to Mir server")
		fmt.Println("error connecting to Mir server")
		os.Exit(1)
	}
	log.Info().Str("url", cfg.Target).Str("status", m.Bus.Status().String()).Msg("msg bus status")
	k.Bind(m)
	k.Bind(log)
	k.Bind(cli.NewConfig(cfg.LogLevel, cfg.Target))
	k.Bind(tui.NewConfig(cfg.LogLevel, cfg.Target))

	return nil
}
