name: Integration Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Install WebSDK dependencies
        run: npm install --prefix ./pkgs/web

      - name: Build WebSDK
        run: npm run build --prefix ./pkgs/web

      - name: Install Web UI dependencies
        run: npm install --prefix ./internal/ui/web

      - name: Build Web UI
        run: npm run build --prefix ./internal/ui/web

      - name: Build
        run: go build -v ./...

      - name: Set up test environment
        run: docker compose -f infra/compose/ci/compose.yaml up -d --wait

      - name: Set up test services
        run: ./scripts/ci_integration_tests.sh

      - name: Test
        run: go test -coverprofile coverage.out -count 1 ./...

      - name: Upload test coverage
        uses: actions/upload-artifact@v4.4.3
        with:
          name: coverage.out
          path: ./coverage.out

      - name: Upload services config and logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: services_config_logs.zip
          path: ./.artifacts/*
          include-hidden-files: true
